### ISSUE TITLE
Integrate Staticman Comments

### ISSUE THREAD

**Issue by theportablegeek** [hightechu/resources#20]
https://staticman.net/docs/

**Comment by VincentTam** [comment]
Unluckily, as reported in https://github.com/eduardoboucas/staticman/issues/296#issuecomment-501987544, the docs *aren't* update.  If you wish to experience Staticman in minutes, you may take a look at [Beautiful Jekyll](https://github.com/daattali/beautiful-jekyll).  If you wish to know more about Staticman v3, you might refer to [my blog about Staticman repo setup](https://vincenttam.gitlab.io/post/2018-09-16-staticman-powered-gitlab-pages/1/).

P.S. I ported Minimal Mistakes' Staticman support into Beautiful Jekyll, and I built @staticmanlab, a public GitLab instance of Staticman.
